import math
import random
from random import randint
import matplotlib.pyplot as plt
import numpy as np
from funkcje_pomocnicze import ModelVerhulstContinuous as MVC
from funkcje_pomocnicze import ModelVerhulstDiscrete as MVD
from funkcje_pomocnicze import CreateChromosoms as createChromosom
from One_Plus_One_Continous import One_Plus_One_Continous
from Mu_Plus_Lambda_Continous import Mu_Plus_Lambda_Continous
from Mu_Comma_Lambda_Continous import Mu_Comma_Lambda_Continous
from One_Plus_One_Discrete import One_Plus_One_Discrete
from Mu_Plus_Lambda_Discrete import Mu_Plus_Lambda_Discrete
from Mu_Comma_Lambda_Discrete import Mu_Comma_Lambda_Discrete

Mu_Comma_Lambda_Discrete(1)